services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: 4ami_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - 4ami_network_dev

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: 4ami_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - 4ami_network_dev

  # NestJS Application (Development Mode)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: 4ami_backend_dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-5000}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_FROM=${MAIL_FROM}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      - AI_AGENT_URL=${AI_AGENT_URL}
      - AI_AGENT_API_KEY=${AI_AGENT_API_KEY}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - UPLOAD_PATH=${UPLOAD_PATH:-./uploads}
    depends_on:
      - postgres
      - redis
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      # Exclude node_modules to use container's version
      - /app/node_modules
    networks:
      - 4ami_network_dev
    command: npm run start:dev

  # pgAdmin - PostgreSQL Administration Tool
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: 4ami_pgadmin_dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - 4ami_network_dev

volumes:
  postgres_data_dev:
  redis_data_dev:
  pgadmin_data_dev:

networks:
  4ami_network_dev:
    driver: bridge
